version: "3"
services:
  worker:
    image: registry.gitlab.com/brahimhamdi/dockercoins/worker
  rng:
    image: registry.gitlab.com/brahimhamdi/dockercoins/rng
  hasher:
    image: registry.gitlab.com/brahimhamdi/dockercoins/hasher
  webui:
    image: brahimhamdi/webui
    ports:
      - 8000:80
  redis:
    image: redis

