version: "3"
services:
  worker:
    image: worker
    build: ./worker
  rng:
    image: rng
    build: ./rng
  hasher:
    image: hasher
    build: ./hasher
  webui:
    image: brahimhamdi/webui
  redis:
    image: redis

